# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'EasyTest'

steps:
- task: NuGetToolInstaller@1

- task: DownloadSecureFile@1
  name: nugetConf
  inputs:
    secureFile: 'nuget.config'

- task: CmdLine@2
  inputs:
    script: |
      echo $(nugetConf.secureFilePath)
      xcopy $(nugetConf.secureFilePath)

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: '$(nugetConf.secureFilePath)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  inputs:
    script: |      
      echo Starting MSSQLLocalDB    
      sqllocaldb start MSSQLLocalDB
      Starting copy EasyTest Files
      xcopy EasyTestBin\DevExpress.ExpressApp.EasyTest.WinAdapter.v19.2.dll XCRM.Win\bin\Debug /Y
      xcopy EasyTestBin\DevExpress.EasyTest.v19.2.dll XCRM.Win\bin\Debug /Y
      xcopy EasyTestBin\DevExpress.ExpressApp.EasyTest.WebAdapter.v19.2.dll XCRM.Web\bin /Y
      xcopy EasyTestBin\DevExpress.EasyTest.v19.2.dll XCRM.Web\bin /Y
      xcopy EasyTestBin\Microsoft.mshtml.dll XCRM.Web\bin /Y
      Starting EasyTests
      EasyTestBin\TestExecutor.v19.2.exe EasyTests  
      echo %errorlevel%
      FINDSTR "Result=""Failed""" EasyTests\TestsLog.xml && (
        Result="Failed" true
        exit 1
        )
      FINDSTR "Result=""Warning""" EasyTests\TestsLog.xml && (
        Result="Warning" true
        exit 1
        )

- task: PublishPipelineArtifact@1
  condition: succeededOrFailed()
  inputs:
    targetPath: '.\EasyTests\'
    artifact: 'TestsResultFiles'
    publishLocation: 'pipeline'